### ISSUE TITLE
[BUG] KDE Multi-Monitor Support

### ISSUE THREAD

**Issue by hsmalley** [Ultramarine-Linux/triage#43]
**Describe the bug**
Using the migrate script broke multi-monitor support on Plasma/KDE

**To Reproduce**
1. Start with a Fedora KDE install
2. Run migration script
3. Reboot

**Expected behavior**
I expected system to behave just like fedora since it should be bug-for-bug compatible. There was no way to enable the other monitors as they just would not show up in the settings at all. I ended up having to manually undo migration script and run a distro sync to get it back to stock fedora. 

**Desktop (please complete the following information):**
 - OS: Ultramarine Linux KDE
 - Version 40

**Additional context**
Aside from the monitor problem everything else looks great!

**Comment by madonuko** [comment]
> I expected system to behave just like fedora since it should be bug-for-bug compatible

… I expect the same too: Ultramarine Linux and Fedora Linux should be bug-for-bug compatible in this case; in fact, I cannot reproduce this issue with my multi-monitor set-up.

Since you said you used the migration script, this might be a kernel/driver regression. Please check that your vanilla Fedora system does not have the same issue after a full system update.

Otherwise, I am absolutely clueless.

**Comment by loneicewolf** [comment]
i couldnt really re-produce it,

**Comment by nothingneko** [comment]
Is this solved?
